apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: cuda-container
      image: nvidia/cuda:9.0-devel
      command: ["/bin/bash", "-c", "--"]
      args:
          - "while true; do sleep 1;done"
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs
